apiVersion: v1
kind: Service
metadata:
  name: eqloginoidc
  labels:
    app: eqloginoidc
    component: oidc-provider
spec:
  type: ClusterIP
  ports:
  - port: 8443
    targetPort: 8443
    protocol: TCP
    name: https
  selector:
    app: eqloginoidc
