---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: eqloginoidc
spec:
  entryPoints:
    - websecure
  routes:
    - match: (PathPrefix(`/auth`) || PathPrefix(`/token`) || PathPrefix(`/userinfo`) || PathPrefix(`/login`) || PathPrefix(`/.well-known`))
      kind: Rule
      services:
        - name: eqloginoidc
          port: 8443
          scheme: http