---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: eqloginoidc
spec:
  entryPoints:
    - websecure
  routes:
    - match: host(`xev.teraptra.net`) && ((PathPrefix(`/auth`) || PathPrefix(`/token`) || PathPrefix(`/userinfo`) || PathPrefix(`/login`) || PathPrefix(`/.well-known`))
      kind: Rule
      services:
        - name: eqloginoidc
          port: 8443
          scheme: https
          serversTransport: mytransport
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: mytransport
  namespace: default

spec:
  serverName: xev.teraptra.net
  insecureSkipVerify: true